"""Pydantic output model for ScaffoldAgent structured outputs."""

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


class ScaffoldOutput(BaseModel):
    """Validated metadata about files generated by ScaffoldAgent.

    ScaffoldAgent is mostly deterministic (template-driven). This model
    captures the metadata about what was generated so downstream agents
    (CoderAgent, SecurityAgent) can trust required files exist before running.
    """

    model_config = ConfigDict(extra="ignore")

    project_root: str = Field(..., min_length=1, description="Relative path to generated project root (e.g. 'project')")
    files_created: List[str] = Field(..., min_length=5, description="All files created under project_root (≥5 required)")
    has_backend: bool = Field(..., description="backend/app/main.py exists")
    has_frontend: bool = Field(..., description="frontend/package.json exists")
    has_supabase: bool = Field(..., description="supabase/schema.sql exists")
    has_docker: bool = Field(..., description="docker-compose.yml exists at project root")
    has_github_actions: bool = Field(..., description=".github/workflows/ci.yml exists")
    backend_framework: str = Field(..., min_length=1, description="Backend framework (e.g. FastAPI)")
    frontend_framework: str = Field(..., min_length=1, description="Frontend framework (e.g. Next.js 14)")
    file_count: int = Field(..., ge=5, description="Total files generated (must match len(files_created))")
