'use client'

import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import AgentChapter from '@/components/fx/AgentPanel'
import Typewriter from '@/components/fx/Typewriter'
import { mayaPRD } from '@/data/simulations'

/* The PRD document typing itself, field by field. */
function PRDSim({ active }: { active: boolean }) {
  const [fieldIdx, setFieldIdx] = useState(0)
  const allDone = fieldIdx >= mayaPRD.length

  useEffect(() => {
    if (!active) setFieldIdx(0)
  }, [active])

  return (
    <div className="px-6 py-7 text-[13px] leading-[1.8] md:px-9 md:py-9 md:text-sm">
      <div
        className="mb-6 text-[11px] uppercase"
        style={{ color: 'var(--w-dim)', letterSpacing: '0.18em' }}
      >
        PRD — generated by Maya · rev 1
      </div>
      <dl className="grid grid-cols-1 gap-y-1 md:grid-cols-[max-content_1fr] md:gap-x-8 md:gap-y-3">
        {mayaPRD.map((f, i) => {
          if (!active || i > fieldIdx) {
            // reserve nothing — fields materialize as they type
            return null
          }
          const isCurrent = i === fieldIdx
          const isLast = i === mayaPRD.length - 1
          const doneValue =
            isLast && !isCurrent ? f.value.replace(/\s✓$/, '') : f.value
          return (
            <div key={f.label} className="contents">
              <dt
                className="whitespace-nowrap font-bold"
                style={{ color: 'var(--cel)' }}
              >
                {f.label}:
              </dt>
              <dd className="mb-2 md:mb-0" style={{ color: 'var(--w)' }}>
                {isCurrent ? (
                  <Typewriter
                    text={f.value}
                    active={active}
                    speed={28}
                    startDelay={i === 0 ? 300 : 120}
                    onDone={() => setFieldIdx((n) => n + 1)}
                  />
                ) : (
                  <span style={{ whiteSpace: 'pre-wrap' }}>
                    {doneValue}
                    {isLast && (
                      <motion.span
                        className="ml-1 inline-block font-bold"
                        style={{ color: 'var(--cel)' }}
                        animate={{
                          scale: [1, 1.25, 1],
                          textShadow: [
                            '0 0 0px rgba(62,180,137,0)',
                            '0 0 14px rgba(62,180,137,0.9)',
                            '0 0 0px rgba(62,180,137,0)',
                          ],
                        }}
                        transition={{
                          duration: 1.8,
                          repeat: Infinity,
                          ease: 'easeInOut',
                        }}
                      >
                        ✓
                      </motion.span>
                    )}
                  </span>
                )}
              </dd>
            </div>
          )
        })}
      </dl>
      {!allDone && active && (
        <span
          aria-hidden
          className="mt-2 inline-block h-[14px] w-[8px] align-middle"
          style={{ background: 'rgba(232,227,210,0.0)' }}
        />
      )}
    </div>
  )
}

export default function S04_Maya() {
  return (
    <AgentChapter
      id="agents"
      eyebrow="// Maya → PMAgent"
      name="Maya"
      role="She writes the spec before anyone writes code."
      glow="fire"
    >
      {(active) => <PRDSim active={active} />}
    </AgentChapter>
  )
}
